---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "service-smssettings"
  description: "SMS settings microservice for pip-services"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

# Performance counters that posts values to log
- descriptor: "pip-services:counters:log:default:1.0"
  level: "trace"

{{#if MEMORY_ENABLED}}
# In-memory persistence. Use only for testing!
- descriptor: "service-smssettings:persistence:memory:default:1.0"
{{/if}}

{{#if FILE_ENABLED}}
# File persistence. Use it for testing of for simple standalone deployments
- descriptor: "service-smssettings:persistence:file:default:1.0"
  path: {{FILE_PATH}}{{#unless FILE_PATH}}"../data/smssettings.json"{{/unless}}
{{/if}}

{{#if MONGO_ENABLED}}
# MongoDB Persistence
- descriptor: "service-smssettings:persistence:mongodb:default:1.0"
  collection: {{MONGO_COLLECTION}}{{#unless MONGO_COLLECTION}}smssettings{{/unless}}
  connection:
    uri: {{{MONGO_SERVICE_URI}}}
    host: {{{MONGO_SERVICE_HOST}}}{{#unless MONGO_SERVICE_HOST}}localhost{{/unless}}
    port: {{MONGO_SERVICE_PORT}}{{#unless MONGO_SERVICE_PORT}}27017{{/unless}}
    database: {{MONGO_DB}}{{#unless MONGO_DB}}app{{/unless}}
  credential:
    username: {{MONGO_USER}}
    password: {{MONGO_PASS}}
{{/if}}

{{#unless MEMORY_ENABLED}}{{#unless FILE_ENABLED}}{{#unless MONGO_ENABLED}}
# Default in-memory persistence
- descriptor: "service-smssettings:persistence:memory:default:1.0"
{{/unless}}{{/unless}}{{/unless}}

# Default controller
- descriptor: "service-smssettings:controller:default:default:1.0"
  options:
    magic_code: {{MAGIC_CODE}}{{#unless MAGIC_CODE}}'123'{{/unless}}
    verify_on_create: {{VERIFY_ON_CREATE}}{{#unless VERIFY_ON_CREATE}}true{{/unless}}
    verify_on_update: {{VERIFY_ON_UPDATE}}{{#unless VERIFY_ON_UPDATE}}true{{/unless}}

# Common HTTP endpoint
- descriptor: "pip-services:endpoint:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080

# HTTP endpoint version 1.0
- descriptor: "service-smssettings:service:commandable-http:default:1.0"
  swagger:
    enable: true
    auto: true

# Heartbeat service
- descriptor: "pip-services:heartbeat-service:http:default:1.0"

# Status service
- descriptor: "pip-services:status-service:http:default:1.0"

# Swagger service
- descriptor: "pip-services:swagger-service:http:default:1.0"